version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    assignees:
      - "ChenZihua-cn"
    labels:
      - "dependencies"
    versioning-strategy: increase
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      css:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      types:
        patterns:
          - "typescript"
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
